experiment:
  dataset: movielens_2k

  data_config:
    strategy: dataset
    dataset_path: ../data/movielens_2k/dataset.tsv 

  #prefiltering:
  #  strategy : user_k_core
  #  core : 30


  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
        folds : 1

  top_k: 50

  evaluation:
    cutoffs: [10] #, 9, 8, 7, 6, 5, 4, 3]
    simple_metrics: [nDCG] # ,Precision,ItemCoverage,EPC,Gini]
    #paired_ttest: True
    #wilcoxon_test: True
    relevance_threshold: 1

  print_results_as_triplets: True
  external_models_path: ../external/models/__init__.py
  models:
    #MostPop:
    #  meta:
    #    verbose: True
    #    save_recs: True

    external.RecUserKNN:
    #ItemKNN:
      meta:
        verbose: True
        save_recs: True
        validation_metric: nDCG@10
      #extra_params: true
      neighbors: [50]
      similarity: cosine
      implementation: standard

    #Random:
    #  meta:
    #    verbose: True
    #    save_recs: True
    #  seed: 42